### ISSUE TITLE
Set up Pipelines

### ISSUE THREAD

**Issue by ericzty** [stevensblueprint/nycmesh-node-visualizer#15]
- [x] docker-compose @miguel-merlin 
- [X] Dockerfile @JonMike8
- [x] docker build action @ericzty
- [x] docker publish action @ericzty 
- [x] lint test @OwenTruong 
- [x] style test @OwenTruong 
- [x] code coverage @maxgreen01

**Comment by miguel-merlin** [comment]
@Arnavpmr

**Comment by miguel-merlin** [comment]
@OwenTruong

**Comment by OwenTruong** [comment]
During the meeting, we discussed that these two tests were of high priority so they have been set up.

**Comment by miguel-merlin** [comment]
Just FYI, Next.js has already lint test incorporated.

**Comment by miguel-merlin** [comment]
@OwenTruong @Arnavpmr I would be great if you guys could set up code coverage before pushing to the main. (Code Coverage is making sure that X% of the new code pushed to the main branch has unit tests)

**Comment by ericzty** [comment]
about.codecov.io

**Comment by OwenTruong** [comment]
Understood!

**Comment by OwenTruong** [comment]
Apologies, I might be a bit slow adding code coverage since I have my midterms earlier this week. I'll try to add that over the weekends.

**Comment by miguel-merlin** [comment]
#40 Docker and Postgress

**Comment by miguel-merlin** [comment]
#42 Cypress and Jest

**Comment by maxgreen01** [comment]
Seems like I'm not able to make any real progress with setting up Codecov because I don't have admin. I'm stuck at the point of adding the repo actions token:
https://app.codecov.io/gh/stevensblueprint/nycmesh-node-visualizer/new

**Comment by miguel-merlin** [comment]
Let me make you an admin temporarily

**Comment by maxgreen01** [comment]
It seems to have worked, so I think you should be good to remove my admin. I was able to add the secret and set up an action file (see 6ad9672), but when running the action itself, this happens (pay close attention to the last few lines):
![image](https://github.com/stevensblueprint/nycmesh-node-visualizer/assets/69012713/95fb368a-9c52-471b-a0fe-da1f9516b640)

I'm not sure how to set up which files should be checked since it appears to be language-specific, but here's all the relevant links I've found about setting that up:
https://docs.codecov.com/docs
https://docs.codecov.com/docs/github-2-getting-a-codecov-account-and-uploading-coverage
https://docs.codecov.com/docs/supported-report-formats

**Comment by miguel-merlin** [comment]
Thanks. I think it is okay if you are getting the error because currently, we have no tests in the repo. Once we set that up we can test if the code coverage works.

**Comment by ericzty** [comment]
let’s push a button to the readme

**Comment by maxgreen01** [comment]
note to self:
test files will be in `test/` dir using Jest framework, and github action should run tests through command line to generate CodeCov report.

relevant links:
https://jestjs.io/docs/cli#--coverageboolean
https://about.codecov.io/blog/how-to-set-up-codecov-with-c-plus-plus-and-github-actions/
https://docs.codecov.com/docs/github-1-setting-and-getting-code-coverage

once this is set up, should be relatively easy to add coverage badges/graphs to the readme:
https://docs.codecov.com/docs/status-badges

**Comment by ericzty** [comment]
Closing this issue as completed, good job all!
